package com.paysonic.tollops;

import com.paysonic.tollops.entity.PassSummaryRecord;
import com.paysonic.tollops.repository.PassSummaryRepository;
import com.paysonic.tollops.service.PassSummaryService;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.when;

public class PassSummaryExcelTest {

    @Test
    public void testExportExcelDoesNotThrow() throws Exception {
        PassSummaryRepository repo = Mockito.mock(PassSummaryRepository.class);
        List<PassSummaryRecord> sampleRecords = List.of(
                new PassSummaryRecord("555555", "Plaza1", LocalDate.of(2026, 9, 15), "Cash", "Monthly Regular", 5L, new BigDecimal("100.00"), 1),
                new PassSummaryRecord("555555", "Plaza1", LocalDate.of(2026, 9, 15), "Cash", "Monthly Exempted", 4L, BigDecimal.ZERO, 2),
                new PassSummaryRecord("555555", "Plaza1", LocalDate.of(2026, 9, 15), "Cash", "Local 10km", 6L, new BigDecimal("50.00"), 3),
                new PassSummaryRecord("555555", "Plaza1", LocalDate.of(2026, 9, 15), "Cash", "Local 20km", 7L, new BigDecimal("80.00"), 4),
                new PassSummaryRecord("555555", "Plaza1", LocalDate.of(2026, 9, 15), "Online", "Monthly Regular", 5L, new BigDecimal("100.00"), 5),
                new PassSummaryRecord("555555", "Plaza1", LocalDate.of(2026, 9, 15), "Online", "Monthly Exempted", 4L, BigDecimal.ZERO, 6),
                new PassSummaryRecord("555555", "Plaza1", LocalDate.of(2026, 9, 15), "Online", "Local 10km", 6L, new BigDecimal("50.00"), 7),
                new PassSummaryRecord("555555", "Plaza1", LocalDate.of(2026, 9, 15), "Online", "Local 20km", 7L, new BigDecimal("80.00"), 8)
        );
        when(repo.findByFilters(any(), any(), any())).thenReturn(sampleRecords);

        PassSummaryService service = new PassSummaryService(repo);
        byte[] excelBytes = service.exportExcel("ALL", LocalDate.of(2026, 9, 1), LocalDate.of(2026, 9, 30));

        assertNotNull(excelBytes);
        assertTrue(excelBytes.length > 0);
        System.out.println("Export Excel Succeeded! Generated bytes: " + excelBytes.length);
    }
}
