// India States and their major cities — used across the project for State/City dropdowns
export const INDIA_STATE_CITY_MAP = {
  'ANDHRA PRADESH': ['VIJAYAWADA', 'VISAKHAPATNAM', 'GUNTUR', 'NELLORE', 'KURNOOL', 'TIRUPATI', 'KAKINADA', 'RAJAHMUNDRY', 'KADAPA', 'ANANTAPUR', 'ELURU', 'ONGOLE', 'CHITTOOR', 'SRIKAKULAM', 'MACHILIPATNAM'],
  'ARUNACHAL PRADESH': ['ITANAGAR', 'NAHARLAGUN', 'PASIGHAT', 'TEZPUR', 'NAMSAI'],
  'ASSAM': ['GUWAHATI', 'SILCHAR', 'DIBRUGARH', 'JORHAT', 'NAGAON', 'TINSUKIA', 'TEZPUR', 'BONGAIGAON', 'KARIMGANJ', 'SIBSAGAR'],
  'BIHAR': ['PATNA', 'GAYA', 'BHAGALPUR', 'MUZAFFARPUR', 'DARBHANGA', 'PURNIA', 'ARRAH', 'BEGUSARAI', 'KATIHAR', 'MUNGER', 'CHAPRA', 'BUXAR', 'HAJIPUR', 'SASARAM', 'SIWAN'],
  'CHANDIGARH': ['CHANDIGARH', 'MOHALI', 'PANCHKULA'],
  'CHHATTISGARH': ['RAIPUR', 'BHILAI', 'BILASPUR', 'KORBA', 'DURG', 'RAIGARH', 'RAJNANDGAON', 'JAGDALPUR', 'AMBIKAPUR', 'DHAMTARI'],
  'DELHI': ['NEW DELHI', 'DELHI', 'NOIDA', 'DWARKA', 'ROHINI', 'PITAMPURA', 'JANAKPURI', 'SAKET', 'LAJPAT NAGAR', 'KAROL BAGH'],
  'GOA': ['PANAJI', 'MARGAO', 'VASCO DA GAMA', 'MAPUSA', 'PONDA', 'BICHOLIM', 'CALANGUTE', 'CANDOLIM'],
  'GUJARAT': ['AHMEDABAD', 'SURAT', 'VADODARA', 'RAJKOT', 'BHAVNAGAR', 'JAMNAGAR', 'GANDHINAGAR', 'JUNAGADH', 'ANAND', 'NADIAD', 'MORBI', 'MEHSANA', 'BHARUCH', 'SURENDRANAGAR', 'VALSAD'],
  'HARYANA': ['GURUGRAM', 'FARIDABAD', 'PANIPAT', 'AMBALA', 'YAMUNANAGAR', 'ROHTAK', 'HISAR', 'KARNAL', 'SONIPAT', 'PANCHKULA', 'BHIWANI', 'SIRSA', 'BAHADURGARH', 'KURUKSHETRA', 'REWARI'],
  'HIMACHAL PRADESH': ['SHIMLA', 'SOLAN', 'MANDI', 'KANGRA', 'DHARAMSHALA', 'HAMIRPUR', 'KULLU', 'MANALI', 'BILASPUR', 'UNA'],
  'JAMMU AND KASHMIR': ['SRINAGAR', 'JAMMU', 'ANANTNAG', 'BARAMULLA', 'SOPORE', 'PULWAMA', 'KATHUA', 'UDHAMPUR', 'RAJOURI'],
  'JHARKHAND': ['RANCHI', 'JAMSHEDPUR', 'DHANBAD', 'BOKARO', 'HAZARIBAGH', 'DEOGHAR', 'GIRIDIH', 'RAMGARH', 'PHUSRO', 'MEDININAGAR'],
  'KARNATAKA': ['BENGALURU', 'MYSURU', 'HUBBALLI', 'MANGALURU', 'BELAGAVI', 'KALABURAGI', 'DAVANAGERE', 'BALLARI', 'VIJAYAPURA', 'SHIVAMOGGA', 'TUMAKURU', 'UDUPI', 'DHARWAD', 'HASSAN', 'BIDAR'],
  'KERALA': ['THIRUVANANTHAPURAM', 'KOCHI', 'KOZHIKODE', 'THRISSUR', 'KOLLAM', 'PALAKKAD', 'KANNUR', 'ALAPPUZHA', 'KOTTAYAM', 'MALAPPURAM', 'KASARAGOD', 'PATHANAMTHITTA', 'IDUKKI', 'WAYANAD'],
  'LADAKH': ['LEH', 'KARGIL'],
  'LAKSHADWEEP': ['KAVARATTI', 'AGATTI', 'ANDROTH'],
  'MADHYA PRADESH': ['BHOPAL', 'INDORE', 'JABALPUR', 'GWALIOR', 'UJJAIN', 'SAGAR', 'RATLAM', 'SATNA', 'DEWAS', 'MURWARA', 'REWA', 'SINGRAULI', 'BURHANPUR', 'CHHINDWARA', 'SHIVPURI'],
  'MAHARASHTRA': ['MUMBAI', 'PUNE', 'NAGPUR', 'NASHIK', 'AURANGABAD', 'SOLAPUR', 'THANE', 'NAVI MUMBAI', 'KOLHAPUR', 'AMRAVATI', 'NANDED', 'LATUR', 'JALGAON', 'AKOLA', 'CHANDRAPUR', 'PIMPRI-CHINCHWAD', 'BHIWANDI', 'SANGLI', 'AHMEDNAGAR', 'RATNAGIRI'],
  'MANIPUR': ['IMPHAL', 'THOUBAL', 'BISHNUPUR', 'CHURACHANDPUR', 'SENAPATI'],
  'MEGHALAYA': ['SHILLONG', 'TURA', 'JOWAI', 'NONGSTOIN'],
  'MIZORAM': ['AIZAWL', 'LUNGLEI', 'CHAMPHAI', 'SERCHHIP'],
  'NAGALAND': ['KOHIMA', 'DIMAPUR', 'MOKOKCHUNG', 'WOKHA', 'ZUNHEBOTO'],
  'ODISHA': ['BHUBANESWAR', 'CUTTACK', 'ROURKELA', 'BERHAMPUR', 'SAMBALPUR', 'PURI', 'BALASORE', 'BHADRAK', 'JHARSUGUDA', 'BARGARH', 'ANGUL', 'KENDUJHAR', 'KORAPUT'],
  'PUDUCHERRY': ['PUDUCHERRY', 'KARAIKAL', 'YANAM', 'MAHE'],
  'PUNJAB': ['LUDHIANA', 'AMRITSAR', 'JALANDHAR', 'PATIALA', 'BATHINDA', 'MOHALI', 'HOSHIARPUR', 'PATHANKOT', 'MOGA', 'FIROZPUR', 'GURDASPUR', 'SANGRUR', 'FARIDKOT', 'MUKTSAR', 'RUPNAGAR'],
  'RAJASTHAN': ['JAIPUR', 'JODHPUR', 'UDAIPUR', 'KOTA', 'AJMER', 'BIKANER', 'ALWAR', 'BHARATPUR', 'SIKAR', 'PALI', 'BARMER', 'NAGAUR', 'CHURU', 'JHUNJHUNU', 'TONK', 'HANUMANGARH', 'BHILWARA'],
  'SIKKIM': ['GANGTOK', 'NAMCHI', 'GYALSHING', 'MANGAN'],
  'TAMIL NADU': ['CHENNAI', 'COIMBATORE', 'MADURAI', 'TIRUCHIRAPPALLI', 'SALEM', 'TIRUNELVELI', 'ERODE', 'VELLORE', 'THOOTHUKKUDI', 'TIRUPPUR', 'DINDIGUL', 'THANJAVUR', 'RANIPET', 'SIVAKASI', 'KRISHNAGIRI', 'NAGERCOIL', 'HOSUR'],
  'TELANGANA': ['HYDERABAD', 'WARANGAL', 'NIZAMABAD', 'KARIMNAGAR', 'KHAMMAM', 'RAMAGUNDAM', 'NALGONDA', 'MAHBUBNAGAR', 'ADILABAD', 'SURYAPET', 'SIDDIPET', 'SANGAREDDY', 'MIRYALAGUDA', 'BHONGIR', 'MANCHERIAL'],
  'TRIPURA': ['AGARTALA', 'DHARMANAGAR', 'UDAIPUR', 'KAILASHAHAR', 'BELONIA'],
  'UTTAR PRADESH': ['LUCKNOW', 'KANPUR', 'AGRA', 'VARANASI', 'MEERUT', 'ALLAHABAD', 'BAREILLY', 'ALIGARH', 'MORADABAD', 'SAHARANPUR', 'GORAKHPUR', 'NOIDA', 'GREATER NOIDA', 'GHAZIABAD', 'MATHURA', 'FIROZABAD', 'JHANSI', 'MUZAFFARNAGAR', 'HAPUR', 'AYODHYA', 'RAMPUR', 'SHAHJAHANPUR', 'AMROHA', 'MAUNATH BHANJAN', 'ETAH'],
  'UTTARAKHAND': ['DEHRADUN', 'HARIDWAR', 'ROORKEE', 'HALDWANI', 'RUDRAPUR', 'KASHIPUR', 'RISHIKESH', 'KOTDWAR', 'SITARGANJ', 'RAMNAGAR'],
  'WEST BENGAL': ['KOLKATA', 'ASANSOL', 'SILIGURI', 'DURGAPUR', 'BARDHAMAN', 'MALDA', 'BAHARAMPUR', 'HABRA', 'KHARAGPUR', 'SHANTIPUR', 'DANKUNI', 'DHULIAN', 'RAIGANJ', 'JALPAIGURI', 'BANKURA', 'MEDINIPUR'],
};

export const INDIA_STATES = Object.keys(INDIA_STATE_CITY_MAP).sort();

export const getCitiesForState = (state) => {
  if (!state) return [];
  return INDIA_STATE_CITY_MAP[state.toUpperCase().trim()] || [];
};
